name: Publish to Nuget

on:
  push:
    branches: [ main ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./src/SrPattif.Danfe/SrPattif.Danfe.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: .NET 5 setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Update version with build ID
      run: |
        BUILD_VERSION="1.0.0.${{ github.run_number }}"
        sed -i "s|<Version>.*</Version>|<Version>${BUILD_VERSION}</Version>|" ${{ env.CAMINHO_PROJETO }}

    - name: Package generation
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push on NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
